# Generated by Django 5.1.6 on 2025-02-27 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0002_initial'),
        ('timeouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timeout',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeoutanswer',
            name='timeout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeouts.timeout'),
        ),
        migrations.AddField(
            model_name='timeouthazard',
            name='timeout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeouts.timeout'),
        ),
        migrations.AddField(
            model_name='timeoutquestionnaire',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='businesses.business'),
        ),
        migrations.AddField(
            model_name='timeoutquestion',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeoutquestions', to='timeouts.timeoutquestionnaire'),
        ),
        migrations.AddField(
            model_name='timeout',
            name='questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timeouts.timeoutquestionnaire'),
        ),
    ]
